package Util

enum class Algorithm {
    RANDOM_WALK,
    RANDOM_SEARCH,
    HEURSITC,
    RANDOM_GREEDY_LOCAL_SEARCH,
    RANDOM_STEEPEST_LOCAL_SEARCH,
    HEURISTIC_GREEDY_LOCAL_SEARCH,
    HEURISTIC_STEEPEST_LOCAL_SEARCH,
    RANDOM_GREEDY_MS_LOCAL_SEARCH,
    RANDOM_STEEPEST_MS_LOCAL_SEARCH,
    HEURISTIC_GREEDY_MS_LOCAL_SEARCH,
    HEURISTIC_STEEPEST_MS_LOCAL_SEARCH,
}