package LocalSearch

import QAP.QAPSolution

abstract class AbstrNeighborhoodExplorer(
    val costEvaluator: Any
): INeighborhoodExplorer {

    @Suppress("UNCHECKED_CAST")
    override fun generateLazyMoves(
        solution: ISolution,
        counter: EvaluationsCounter
    ): List<LazyEvaluatedMove> {
        return try {
            val moves = generateMoves(solution)
            val typedEvaluator = costEvaluator as ICostEvaluator<ISolution, IMove>

            moves.map { move ->
                LazyEvaluatedMove(move, {
                    typedEvaluator.evaluateDelta(solution, move)
                }, counter)
            }
        } catch (e: ClassCastException) {
            throw IllegalStateException(
                "Cost evaluator type mismatch in ${this::class.simpleName}. " +
                        "Expected evaluator compatible with ${solution::class.simpleName} and move types generated by this explorer.",
                e
            )
        }
    }

    @Suppress("UNCHECKED_CAST")
    override fun generateLazyRandomMove(solution: ISolution, counter: EvaluationsCounter): LazyEvaluatedMove {
        return try {
            val move = generateRandomMove(solution)
            val typedEvaluator = costEvaluator as ICostEvaluator<ISolution, IMove>

            LazyEvaluatedMove(move, {
                typedEvaluator.evaluateDelta(solution, move)
            }, counter)
        } catch (e: ClassCastException) {
            throw IllegalStateException(
                "Cost evaluator type mismatch in ${this::class.simpleName}. " +
                        "Expected evaluator compatible with ${solution::class.simpleName} and move types generated by this explorer.",
                e
            )
        }
    }
}