package LocalSearch

import LocalSearch.Representations.ISolution

abstract class AbstrNeighborhoodExplorer(
    val costEvaluator: Any
): INeighborhoodExplorer {

    override fun generateLazyMoves(
        solution: ISolution,
        counter: EvaluationsCounter
    ): List<LazyEvaluatedMove> {
        return when (val result = generateLazy(solution, counter) { generateMoves(solution) }) {
            is LazyMoveResult.Multiple -> result.moves
            is LazyMoveResult.Single -> listOf(result.move)
        }
    }

    override fun generateLazyRandomMove(
        solution: ISolution,
        counter: EvaluationsCounter
    ): LazyEvaluatedMove {
        return when (val result = generateLazy(solution, counter) { generateRandomMove(solution) }) {
            is LazyMoveResult.Single -> result.move
            is LazyMoveResult.Multiple -> result.moves.firstOrNull()
                ?: throw IllegalStateException("Expected at least one move from generateRandomMove")
        }
    }

    @Suppress("UNCHECKED_CAST")
    private fun generateLazy(
        solution: ISolution,
        counter: EvaluationsCounter,
        moveGenerator: () -> Any
    ): LazyMoveResult {
        return try {
            val result = moveGenerator()
            val typedEvaluator = costEvaluator as ICostEvaluator<ISolution, IMove>

            when (result) {
                is IMove -> LazyMoveResult.Single(
                    LazyEvaluatedMove(result, {
                        typedEvaluator.evaluateDelta(solution, result)
                    }, counter)
                )

                is List<*> -> {
                    val moves = result.map {
                        val move = it as IMove
                        LazyEvaluatedMove(move, {
                            typedEvaluator.evaluateDelta(solution, move)
                        }, counter)
                    }
                    LazyMoveResult.Multiple(moves)
                }

                else -> throw IllegalArgumentException(
                    "Unsupported move type: ${result::class.simpleName}"
                )
            }
        } catch (e: ClassCastException) {
            throw IllegalStateException(
                "Cost evaluator type mismatch in ${this::class.simpleName}. " +
                        "Expected evaluator compatible with ${solution::class.simpleName} and move types generated by this explorer.",
                e
            )
        }
    }
}